upload_max_filesize = 16M
post_max_size = 64M
memory_limit = 1024M
max_execution_time = 60
expose_php = Off

log_errors = On
error_log = /var/log/php_errors.log
display_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

; Restringe funções sensíveis
disable_functions = exec,passthru,shell_exec,system,proc_open,popen,parse_ini_file,show_source

date.timezone = America/Bahia

; OPcache otimizado para produção
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
opcache.revalidate_freq=0

; Xdebug desativado
zend_extension=xdebug.so
xdebug.mode=off
