services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starterkit-app
    restart: always
    ports:
      - '8001:80'
      - '3000:3000'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - .:/var/www/html
      - ./docker/NGINX/default.conf:/etc/nginx/sites-available/default
      - ./docker/SUPERVISOR/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - db
      - redis
      - mailpit
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - CHOKIDAR_USEPOLLING=true
  
  db:
    image: postgres:latest
    container_name: starterkit-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=starterkit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/PGSQL:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: starterkit-redis
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pg_data:
    driver: local
