
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV:-development}
    container_name: starterkit-app
    restart: always
    ports:
      - '3000:3000'
      - '5173:5173'
    volumes:
      - .:/var/www/html
      - ./docker/SUPERVISOR/supervisord.conf:/etc/supervisord.conf
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
      - CHOKIDAR_USEPOLLING=true
      - PHP_ENABLE_XDEBUG=0
    networks:
      - starterkit-network
    depends_on:
      - db
      - redis
      - mailpit

  nginx:
    image: nginx:1.27.4-alpine
    container_name: starterkit-nginx
    restart: always
    ports:
      - '8001:80'
    volumes:
      - .:/var/www/html
      - ./docker/NGINX/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - starterkit-network

  db:
    image: postgres:17.4-alpine
    container_name: starterkit-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=starterkit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/PGSQL:/docker-entrypoint-initdb.d
    networks:
      - starterkit-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.4-alpine
    container_name: starterkit-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - starterkit-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:v1.15.1
    container_name: starterkit-mailpit
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - starterkit-network

volumes:
  pg_data:
    driver: local

networks:
  starterkit-network:
    driver: bridge
